name: libero-inspect
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - h5py
  - matplotlib
  - ipykernel
  - jupyterlab

  # optional but very useful
  - tqdm
  - pillow

  - pip
