project_name: Optimization Algorithms for Machine Learning
snapshot_date: '2026-01-07'
components:

- id: pytorch
  name: Pytorch
  version: 2.7.1
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/torch/2.7.1/
  declared_license: BSD
  declared_function: Train neural networks

- id: torchvision
  name: Torchvision
  version: 0.22.1
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/torchvision/0.22.1/
  declared_license: BSD
  declared_function: Train neural networks

- id: numpy
  name: Numpy
  version: 1.26.4
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/numpy/1.26.4/
  declared_license: BSD
  declared_function: Helper for pytorch

- id: wandb
  name: wandb
  version: 0.19.11
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/wandb/0.19.11/
  declared_license: MIT
  declared_function: Logging

- id: matplotlib
  name: Matplotlib
  version: 3.10.3
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/matplotlib/3.10.3/
  declared_license: PSF
  declared_function: visualisation

- id: hydra
  name: Hydra
  version: 1.3.2
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/hydra-core/
  declared_license: MIT License
  declared_function: configs

- id: pandas
  name: Pandas
  version: 2.2.3
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/pandas/2.2.3/
  declared_license: BSD
  declared_function: Data analyses
