project_name: 4D Reconstruction and Volume Estimation
snapshot_date: '2026-01-07'
components:

- id: pytorch
  name: PyTorch
  version: 2.9.1
  environment: Python package (PyPI)
  distribution_channels:
  - type: other
    url: https://pytorch.org/
  declared_license: BSD 3-Clause
  declared_function: operations and training neural networks on GPUs

- id: torchvision
  name: TorchVision
  version: 0.24.1
  environment: Python package (PyPI)
  distribution_channels:
  - type: other
    url: https://pytorch.org/vision
  declared_license: BSD 3-Clause
  declared_function: ''

- id: pytorch3d
  name: PyTorch3D
  version: 0.7.4
  environment: Python package (PyPI)
  distribution_channels:
  - type: other
    url: https://pytorch3d.org
  declared_license: BSD License
  declared_function: rendering (meshes, point clouds, cameras) tightly

- id: deepspeed
  name: DeepSpeed
  version: 0.18.2
  environment: Built from source (GitHub)
  distribution_channels:
  - type: github
    url: https://github.com/microsoft/DeepSpeed
  declared_license: MIT License
  declared_function: ''

- id: open3d
  name: Open3D
  version: 0.19.0
  environment: Built from source (GitHub)
  distribution_channels:
  - type: github
    url: https://github.com/isl-org/Open3D
  declared_license: MIT License
  declared_function: voxel grids) and visualization, used for geometry

- id: opencv-python-opencv-python
  name: OpenCV-Python (opencv-python)
  version: 4.12.0.88
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/opencv-python/
  declared_license: ''
  declared_function: processing (filters, feature detection, geometric

- id: numpy
  name: NumPy
  version: 2.3.5
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/numpy/2.3.5/
  declared_license: BSD License
  declared_function: algebra, random numbers) underpinning most

- id: scipy
  name: SciPy
  version: 1.16.3
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/scipy/
  declared_license: BSD License
  declared_function: integration, interpolation, signal and image

- id: pandas
  name: pandas
  version: 2.3.3
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/pandas/
  declared_license: BSD 3-Clause License
  declared_function: and heterogeneous data (data cleaning,

- id: scikit-learn
  name: scikit-learn
  version: 1.7.2
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/scikit-learn/1.7.2/
  declared_license: BSD 3-Clause License
  declared_function: (classification, regression, clustering,

- id: scikit-image
  name: scikit-image
  version: 0.25.2
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/scikit-image/0.25.2/
  declared_license: BSD 3-Clause License
  declared_function: segmentation, morphology, feature extraction) on

- id: matplotlib
  name: Matplotlib
  version: 3.10.7
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/matplotlib/3.10.7/
  declared_license: Matplotlib license (BSD-compatible)
  declared_function: figures (used for diagnostics, result plots,

- id: seaborn
  name: Seaborn
  version: 0.13.2
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/seaborn/
  declared_license: BSD 3-Clause License
  declared_function: Matplotlib and pandas for quick, publication-ready

- id: weights-biases-wandb
  name: Weights & Biases (wandb)
  version: 0.23.1
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/wandb/
  declared_license: MIT License
  declared_function: ''

- id: hydra-hydra-core
  name: Hydra (hydra-core)
  version: 1.3.2
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/hydra-core/
  declared_license: MIT License
  declared_function: experiments (config composition, overrides, multi-

- id: tqdm
  name: tqdm
  version: 4.67.1
  environment: Python package (PyPI)
  distribution_channels:
  - type: pypi
    url: https://pypi.org/project/tqdm/
  declared_license: MIT License
  declared_function: processing in Python (useful for monitoring long
