name: /ibex/project/c2320/dataset-check/robomind/envs/robomind
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=h0c1763c_0
  - libuuid=2.41.2=h5347b49_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - comm==0.2.3
      - cycler==0.12.1
      - debugpy==1.8.18
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h5py==3.15.1
      - hf-transfer==0.1.9
      - idna==3.11
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lerobot==0.4.2
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - toml==0.10.2
      - tornado==6.5.3
      - traitlets==5.14.3
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /ibex/project/c2320/dataset-check/robomind/envs/robomind
